#!/bin/bash

LICENSE_HEADER="/*
 * Copyright (C) 2024 Marian Pecqueur
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */"

# Find all .dart files and add the header if not already present
find . -type f -name "*.dart" | while read file; do
  if ! grep -q "GNU General Public License" "$file"; then
    echo "$LICENSE_HEADER" | cat - "$file" > temp && mv temp "$file"
    echo "Added license to: $file"
  fi
done

echo "License added to all Dart files."

