deployments:
  environmentMapping:
    development:
      - "development"
      - "dev*"
    testing:
      - "android-testing"
      - "ios-testflight"
      - "ios-testflight-open-beta"
      - "test*"
    staging:
      - "staging"
      - "stage*"
      - "preprod"
      - "pre-prod"
    production:
      - "android-production"
      - "ios-app-store"
      - "production"
      - "prod*"
